version: '3'

interval: 1000ms

tasks:
  default:
    deps:
      - test
      - run
  test:
    desc: Run all tests
    cmds:
      - go test ./...
  run:
    desc: Run the application in the current directory
    cmds:
      - go run ./...
    
